# Generated by Django 3.0.5 on 2021-02-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210220_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'user'), (2, 'moderator'), (3, 'admin')], null=True),
        ),
    ]
