# Generated by Django 3.0.5 on 2021-02-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210219_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='title',
        ),
    ]
