# Generated by Django 3.0.5 on 2021-02-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_genre_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='titles',
            field=models.ManyToManyField(db_table='genre_title', to='api.Title'),
        ),
    ]
