# Generated by Django 3.0.5 on 2021-02-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_genre_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='titles',
        ),
        migrations.AddField(
            model_name='genre',
            name='title',
            field=models.ManyToManyField(to='api.Title'),
        ),
    ]
